# Generated by Django 4.2.13 on 2024-05-28 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioCustomizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='endereço de email')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('endereco', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=20)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEmprestimo', models.DateField(auto_now_add=True)),
                ('devolucaoPrevista', models.DateField()),
                ('dataDevolucao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'PENDENTE'), ('A', 'APROVADO'), ('R', 'RECUSADO'), ('C', 'CANCELADO')], max_length=20)),
                ('usuarioFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimo_usuariocustomizado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='GeneroLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('nota', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantidade', models.IntegerField()),
                ('descricao', models.TextField()),
                ('editora', models.CharField(max_length=30)),
                ('idade', models.CharField(choices=[('L', 'LIVRE'), ('10', '10 anos'), ('12', '12 anos'), ('14', '14 anos'), ('16', '16 anos'), ('18', '18 anos')], max_length=35)),
                ('dataLancamento', models.DateField(auto_now_add=True)),
                ('publicacao', models.DateField()),
                ('numeroPaginas', models.IntegerField()),
                ('formato', models.CharField(choices=[('E', 'EBOOK'), ('F', 'FÍSICO')], max_length=30)),
                ('codEdicao', models.CharField(max_length=25)),
                ('aprovado', models.CharField(choices=[('P', 'PENDENTE'), ('C', 'CANCELADO'), ('A', 'APROVADO')], max_length=25)),
                ('GeneroLivroFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genero', to='emprestimo.generolivro')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorLivro', to=settings.AUTH_USER_MODEL)),
                ('fotoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotoLivro', to='emprestimo.foto')),
            ],
        ),
        migrations.CreateModel(
            name='EmprestimoLivros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emprestimoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimoEmprestimoLivro', to='emprestimo.emprestimo')),
                ('livroFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livroEmprestimoLivro', to='emprestimo.livros')),
            ],
        ),
    ]
